%{
This code aims to save time to load data from 
Updated Weiss Optical Data Transfer - 082924.xlsx

this code is very hard coded, can be optimized
%}

time_norm = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','CtHbO2','Range','V6:V3148');
time_software = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','CtHbO2','Range','W6:W3148');

CtHbO2_treatment = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','CtHbO2','Range','A6:J3148');
CtHbO2_placebo = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','CtHbO2','Range','N6:U3148');

CtHb_treatment = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','CtHb','Range','A6:J3126');
CtHb_placebo = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','CtHb','Range','N6:U3126');

CtHbTot_treatment = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','CtHbTot','Range','A6:J3148');
CtHbTot_placebo = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','CtHbTot','Range','N6:U3148');

aCMRO2_treatment = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','aCMRO2','Range','A6:J3148');
aCMRO2_placebo = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','aCMRO2','Range','N6:U3148');

aCBF_treatment = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','aCBF','Range','A6:J3126');
aCBF_placebo = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','aCBF','Range','N6:U3126');

rCtHbO2_treatment = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','Relative CtHbO2','Range','A6:J3148');
rCtHbO2_placebo = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','Relative CtHbO2','Range','N6:U3148');

rCtHb_treatment = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','Relative CtHb','Range','A6:J3148');
rCtHb_placebo = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','Relative CtHb','Range','N6:U3148');

rCtHbTot_treatment = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','Relative CtHbTot','Range','A6:J3148');
rCtHbTot_placebo = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','Relative CtHbTot','Range','N6:U3148');

rRatio_treatment = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','rRatio','Range','A6:J3148');
rRatio_placebo = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','rRatio','Range','N6:U3148');


renee_rCMRO2_treatment = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','Relative CMRO2 (My Code)','Range','A6:J3148');
renee_rCMRO2_placebo = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','Relative CMRO2 (My Code)','Range','N6:U3148');

renee_rCBF_treatment = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','Relative CBF (My Code)','Range','A6:J3148');
renee_rCBF_placebo = readmatrix('Updated Weiss Optical Data Transfer - 082924.xlsx',...
    'Sheet','Relative CBF (My Code)','Range','N6:U3148');